apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: L3-workflow-boundary
on:
  workflow_dispatch:
jobs:
  scan-job:
      outputs:
         policy-subject: ${{ steps.gosec-step.outputs.policy-subject }}
      steps:
        - name: checkout-source-code
          uses: cloudbees-io/checkout@v2

        - name: Run Gosec Scan
          id: gosec-step
          uses: cloudbees-io/gosec-plugin

        - name: Print policy input
          uses: docker://alpine:latest
          shell: sh
          env:
            ORG: ${{ cloudbees.org.id }}
            ACCESS_KEY: ${{ cloudbees.api.token }}
            URL: ${{ cloudbees.api.url }}
            POLICY_SUBJECT: ${{ steps.gosec-step.outputs.policy-subject }}
          run: |
            echo "$URL"
            echo "$ORG"
            echo "Authorization: Bearer $ACCESS_KEY"
            echo "$POLICY_SUBJECT"
  independent-job:
    steps:
      - name: Run step
        uses: docker://alpine:3.18
        run: echo "independent-job running"
  post-scan-job:
    needs:
      - scan-job
    steps:
      - name: Run step
        uses: docker://alpine:3.18
        run: echo "post-scan-job running"
